name: dart_openai_client
description: A clean, modular Dart client for OpenAI-compatible APIs with full support for function calling (tool calling) capabilities
version: 0.1.0
homepage: https://github.com/yourusername/dart-openai-client

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  puppeteer: ^3.19.0

dev_dependencies:
  test: ^1.26.0
  lints: ^3.0.0
